[package]
name = "miden-project"
version.workspace = true
description = "Interface for working with Miden projects"
documentation = "https://docs.rs/miden-project"
readme = "README.md"
categories = ["compilers", "no-std"]
keywords = ["project", "miden"]
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true
edition.workspace = true

[features]
default = ["std", "serde"]
arbitrary = ["std", "dep:proptest-derive", "dep:proptest", "miden-assembly-syntax/arbitrary"]
resolver = ["std", "dep:pubgrub", "dep:smallvec"]
std = ["miden-assembly-syntax/std", "serde/std", "thiserror/std", "toml/std"]
serde = ["dep:serde", "dep:serde-untagged", "miden-assembly-syntax/serde", "miden-core/serde"]

[dependencies]
miden-assembly-syntax.workspace = true
miden-core.workspace = true
proptest = { workspace = true, optional = true }
proptest-derive = { workspace = true, optional = true }
pubgrub = { version = "0.3", optional = true }
serde = { workspace = true, optional = true }
serde-untagged = { workspace = true, optional = true }
smallvec = { workspace = true, optional = true }
thiserror.workspace = true
toml = { version = "1.0", default-features = false, features = ["serde", "parse"] }

[dev-dependencies]
miden-core.workspace = true
# serde_json is used by miden-test-serde-macros generated code
serde_json.workspace = true
toml = { version = "1.0", default-features = false, features = ["std", "serde", "parse"] }

[package.metadata.cargo-udeps.ignore]
# miden-test-serde-macros generates code that uses serde_json
normal = ["serde_json"]

[lints.rust]
# This is needed until this warning appears in stable when this is commented out. Currently, it
# appears only on nightly, as a side effect of code generated by miette. If we use
# `#[expect(unused_assignments)] in those modules, we get warnings on stable, but not on nightly.
# If we don't do that, we get no warnings on stable, but we do on nightly. Rather than mess about
# with build scripts and such, we just disable this warning for now, as it is essentially useless
# until we get the same behavior on stable and nightly
unused_assignments = "allow"
