[package]
name = "miden-enum-thispatch"
version = "0.1.0"
description = "Proc macro to derive enum thispatch trait implementations (thispatched enum_dispatch)"
readme = "README.md"
categories = ["development-tools::procedural-macro-helpers", "no-std"]
keywords = ["enum", "thispatch", "proc-macro", "derive", "enum_dispatch"]
publish = false
license.workspace = true
authors.workspace = true
homepage.workspace = true
repository.workspace = true
rust-version.workspace = true
edition.workspace = true

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0"
quote = "1.0"
syn = { version = "1.0", features = ["derive", "extra-traits", "full"] }