name: Trigger Aggregator Docs Rebuild

on:
  push:
    branches: [next]
    paths:
      - "docs/**"

permissions: {}

jobs:
  notify:
    runs-on: ubuntu-latest

    permissions: {}

    steps:
      - name: Send repository_dispatch to aggregator
        uses: peter-evans/repository-dispatch@73ca9d9f4f806f6470bf0a2c4245a7d14df16b37
        with:
          # PAT (Personal Access Token) that grants permission to trigger the rebuild workflow at the docs repository
          token: ${{ secrets.DOCS_REPO_TOKEN }}
          repository: ${{ vars.DOCS_AGGREGATOR_REPO }}
          event-type: rebuild
